pub(crate) const LINK_GRAPH_CACHE_VALKEY_URL_ENV: &str = "VALKEY_URL";
pub(crate) const LINK_GRAPH_VALKEY_KEY_PREFIX_ENV: &str =
    "XIUXIAN_WENDAO_LINK_GRAPH_VALKEY_KEY_PREFIX";
pub(crate) const LINK_GRAPH_VALKEY_TTL_SECONDS_ENV: &str =
    "XIUXIAN_WENDAO_LINK_GRAPH_VALKEY_TTL_SECONDS";
pub(crate) const DEFAULT_LINK_GRAPH_VALKEY_KEY_PREFIX: &str = "xiuxian_wendao:link_graph:index";
pub(crate) const LINK_GRAPH_RELATED_MAX_CANDIDATES_ENV: &str =
    "XIUXIAN_WENDAO_LINK_GRAPH_RELATED_MAX_CANDIDATES";
pub(crate) const LINK_GRAPH_RELATED_MAX_PARTITIONS_ENV: &str =
    "XIUXIAN_WENDAO_LINK_GRAPH_RELATED_MAX_PARTITIONS";
pub(crate) const LINK_GRAPH_RELATED_TIME_BUDGET_MS_ENV: &str =
    "XIUXIAN_WENDAO_LINK_GRAPH_RELATED_TIME_BUDGET_MS";
pub(crate) const LINK_GRAPH_AGENTIC_SUGGESTED_LINK_MAX_ENTRIES_ENV: &str =
    "XIUXIAN_WENDAO_LINK_GRAPH_AGENTIC_SUGGESTED_LINK_MAX_ENTRIES";
pub(crate) const LINK_GRAPH_AGENTIC_SUGGESTED_LINK_TTL_SECONDS_ENV: &str =
    "XIUXIAN_WENDAO_LINK_GRAPH_AGENTIC_SUGGESTED_LINK_TTL_SECONDS";
pub(crate) const LINK_GRAPH_AGENTIC_SEARCH_INCLUDE_PROVISIONAL_DEFAULT_ENV: &str =
    "XIUXIAN_WENDAO_LINK_GRAPH_AGENTIC_SEARCH_INCLUDE_PROVISIONAL_DEFAULT";
pub(crate) const LINK_GRAPH_AGENTIC_SEARCH_PROVISIONAL_LIMIT_ENV: &str =
    "XIUXIAN_WENDAO_LINK_GRAPH_AGENTIC_SEARCH_PROVISIONAL_LIMIT";
pub(crate) const LINK_GRAPH_AGENTIC_EXPANSION_MAX_WORKERS_ENV: &str =
    "XIUXIAN_WENDAO_LINK_GRAPH_AGENTIC_EXPANSION_MAX_WORKERS";
pub(crate) const LINK_GRAPH_AGENTIC_EXPANSION_MAX_CANDIDATES_ENV: &str =
    "XIUXIAN_WENDAO_LINK_GRAPH_AGENTIC_EXPANSION_MAX_CANDIDATES";
pub(crate) const LINK_GRAPH_AGENTIC_EXPANSION_MAX_PAIRS_PER_WORKER_ENV: &str =
    "XIUXIAN_WENDAO_LINK_GRAPH_AGENTIC_EXPANSION_MAX_PAIRS_PER_WORKER";
pub(crate) const LINK_GRAPH_AGENTIC_EXPANSION_TIME_BUDGET_MS_ENV: &str =
    "XIUXIAN_WENDAO_LINK_GRAPH_AGENTIC_EXPANSION_TIME_BUDGET_MS";
pub(crate) const LINK_GRAPH_AGENTIC_EXECUTION_WORKER_TIME_BUDGET_MS_ENV: &str =
    "XIUXIAN_WENDAO_LINK_GRAPH_AGENTIC_EXECUTION_WORKER_TIME_BUDGET_MS";
pub(crate) const LINK_GRAPH_AGENTIC_EXECUTION_PERSIST_SUGGESTIONS_DEFAULT_ENV: &str =
    "XIUXIAN_WENDAO_LINK_GRAPH_AGENTIC_EXECUTION_PERSIST_SUGGESTIONS_DEFAULT";
pub(crate) const LINK_GRAPH_AGENTIC_EXECUTION_PERSIST_RETRY_ATTEMPTS_ENV: &str =
    "XIUXIAN_WENDAO_LINK_GRAPH_AGENTIC_EXECUTION_PERSIST_RETRY_ATTEMPTS";
pub(crate) const LINK_GRAPH_AGENTIC_EXECUTION_IDEMPOTENCY_SCAN_LIMIT_ENV: &str =
    "XIUXIAN_WENDAO_LINK_GRAPH_AGENTIC_EXECUTION_IDEMPOTENCY_SCAN_LIMIT";
pub(crate) const LINK_GRAPH_AGENTIC_EXECUTION_RELATION_ENV: &str =
    "XIUXIAN_WENDAO_LINK_GRAPH_AGENTIC_EXECUTION_RELATION";
pub(crate) const LINK_GRAPH_AGENTIC_EXECUTION_AGENT_ID_ENV: &str =
    "XIUXIAN_WENDAO_LINK_GRAPH_AGENTIC_EXECUTION_AGENT_ID";
pub(crate) const LINK_GRAPH_AGENTIC_EXECUTION_EVIDENCE_PREFIX_ENV: &str =
    "XIUXIAN_WENDAO_LINK_GRAPH_AGENTIC_EXECUTION_EVIDENCE_PREFIX";
pub(crate) const LINK_GRAPH_RETRIEVAL_MODE_ENV: &str = "XIUXIAN_WENDAO_LINK_GRAPH_RETRIEVAL_MODE";
pub(crate) const LINK_GRAPH_CANDIDATE_MULTIPLIER_ENV: &str =
    "XIUXIAN_WENDAO_LINK_GRAPH_CANDIDATE_MULTIPLIER";
pub(crate) const LINK_GRAPH_MAX_SOURCES_ENV: &str = "XIUXIAN_WENDAO_LINK_GRAPH_MAX_SOURCES";
pub(crate) const LINK_GRAPH_HYBRID_MIN_HITS_ENV: &str = "XIUXIAN_WENDAO_LINK_GRAPH_HYBRID_MIN_HITS";
pub(crate) const LINK_GRAPH_HYBRID_MIN_TOP_SCORE_ENV: &str =
    "XIUXIAN_WENDAO_LINK_GRAPH_HYBRID_MIN_TOP_SCORE";
pub(crate) const LINK_GRAPH_ROWS_PER_SOURCE_ENV: &str = "XIUXIAN_WENDAO_LINK_GRAPH_ROWS_PER_SOURCE";
pub(crate) const LINK_GRAPH_SEMANTIC_SUMMARY_ONLY_ENV: &str =
    "XIUXIAN_WENDAO_LINK_GRAPH_SEMANTIC_SUMMARY_ONLY";
pub(crate) const LINK_GRAPH_SEMANTIC_MIN_VECTOR_SCORE_ENV: &str =
    "XIUXIAN_WENDAO_LINK_GRAPH_SEMANTIC_MIN_VECTOR_SCORE";
pub(crate) const DEFAULT_LINK_GRAPH_RELATED_MAX_CANDIDATES: usize = 4096;
pub(crate) const DEFAULT_LINK_GRAPH_RELATED_MAX_PARTITIONS: usize = 8;
pub(crate) const DEFAULT_LINK_GRAPH_RELATED_TIME_BUDGET_MS: f64 = 250.0;
pub(crate) const DEFAULT_LINK_GRAPH_RETRIEVAL_MODE: &str = "hybrid";
pub(crate) const DEFAULT_LINK_GRAPH_CANDIDATE_MULTIPLIER: usize = 4;
pub(crate) const DEFAULT_LINK_GRAPH_MAX_SOURCES: usize = 8;
pub(crate) const DEFAULT_LINK_GRAPH_HYBRID_MIN_HITS: usize = 2;
pub(crate) const DEFAULT_LINK_GRAPH_HYBRID_MIN_TOP_SCORE: f64 = 0.25;
pub(crate) const DEFAULT_LINK_GRAPH_ROWS_PER_SOURCE: usize = 8;
pub(crate) const DEFAULT_LINK_GRAPH_AGENTIC_SUGGESTED_LINK_MAX_ENTRIES: usize = 2000;
pub(crate) const DEFAULT_LINK_GRAPH_AGENTIC_SEARCH_PROVISIONAL_LIMIT: usize = 50;
pub(crate) const DEFAULT_LINK_GRAPH_AGENTIC_EXPANSION_MAX_WORKERS: usize = 4;
pub(crate) const DEFAULT_LINK_GRAPH_AGENTIC_EXPANSION_MAX_CANDIDATES: usize = 256;
pub(crate) const DEFAULT_LINK_GRAPH_AGENTIC_EXPANSION_MAX_PAIRS_PER_WORKER: usize = 128;
pub(crate) const DEFAULT_LINK_GRAPH_AGENTIC_EXPANSION_TIME_BUDGET_MS: f64 = 250.0;
pub(crate) const DEFAULT_LINK_GRAPH_AGENTIC_EXECUTION_WORKER_TIME_BUDGET_MS: f64 = 120.0;
pub(crate) const DEFAULT_LINK_GRAPH_AGENTIC_EXECUTION_PERSIST_SUGGESTIONS_DEFAULT: bool = false;
pub(crate) const DEFAULT_LINK_GRAPH_AGENTIC_EXECUTION_PERSIST_RETRY_ATTEMPTS: usize = 2;
pub(crate) const DEFAULT_LINK_GRAPH_AGENTIC_EXECUTION_IDEMPOTENCY_SCAN_LIMIT: usize = 2000;
pub(crate) const DEFAULT_LINK_GRAPH_AGENTIC_EXECUTION_RELATION: &str = "related_to";
pub(crate) const DEFAULT_LINK_GRAPH_AGENTIC_EXECUTION_AGENT_ID: &str = "qianhuan-architect";
pub(crate) const DEFAULT_LINK_GRAPH_AGENTIC_EXECUTION_EVIDENCE_PREFIX: &str =
    "agentic expansion bridge candidate";
