pub(crate) const DEFAULT_LINK_GRAPH_VALKEY_KEY_PREFIX: &str =
    xiuxian_wendao_runtime::runtime_config::DEFAULT_LINK_GRAPH_VALKEY_KEY_PREFIX;
#[allow(dead_code)]
pub(crate) const LINK_GRAPH_RETRIEVAL_MODE_ENV: &str = "XIUXIAN_WENDAO_LINK_GRAPH_RETRIEVAL_MODE";
#[allow(dead_code)]
pub(crate) const LINK_GRAPH_CANDIDATE_MULTIPLIER_ENV: &str =
    xiuxian_wendao_runtime::runtime_config::LINK_GRAPH_CANDIDATE_MULTIPLIER_ENV;
#[allow(dead_code)]
pub(crate) const LINK_GRAPH_MAX_SOURCES_ENV: &str =
    xiuxian_wendao_runtime::runtime_config::LINK_GRAPH_MAX_SOURCES_ENV;
#[allow(dead_code)]
pub(crate) const LINK_GRAPH_HYBRID_MIN_HITS_ENV: &str =
    xiuxian_wendao_runtime::runtime_config::LINK_GRAPH_HYBRID_MIN_HITS_ENV;
#[allow(dead_code)]
pub(crate) const LINK_GRAPH_HYBRID_MIN_TOP_SCORE_ENV: &str =
    xiuxian_wendao_runtime::runtime_config::LINK_GRAPH_HYBRID_MIN_TOP_SCORE_ENV;
#[allow(dead_code)]
pub(crate) const LINK_GRAPH_ROWS_PER_SOURCE_ENV: &str =
    xiuxian_wendao_runtime::runtime_config::LINK_GRAPH_ROWS_PER_SOURCE_ENV;
pub(crate) const LINK_GRAPH_JULIA_RERANK_BASE_URL_ENV: &str =
    "XIUXIAN_WENDAO_LINK_GRAPH_JULIA_RERANK_BASE_URL";
pub(crate) const LINK_GRAPH_JULIA_RERANK_ROUTE_ENV: &str =
    "XIUXIAN_WENDAO_LINK_GRAPH_JULIA_RERANK_ROUTE";
pub(crate) const LINK_GRAPH_JULIA_RERANK_HEALTH_ROUTE_ENV: &str =
    "XIUXIAN_WENDAO_LINK_GRAPH_JULIA_RERANK_HEALTH_ROUTE";
pub(crate) const LINK_GRAPH_JULIA_RERANK_SCHEMA_VERSION_ENV: &str =
    "XIUXIAN_WENDAO_LINK_GRAPH_JULIA_RERANK_SCHEMA_VERSION";
pub(crate) const LINK_GRAPH_JULIA_RERANK_TIMEOUT_SECS_ENV: &str =
    "XIUXIAN_WENDAO_LINK_GRAPH_JULIA_RERANK_TIMEOUT_SECS";
pub(crate) const LINK_GRAPH_JULIA_RERANK_ANALYZER_STRATEGY_ENV: &str =
    "XIUXIAN_WENDAO_LINK_GRAPH_JULIA_RERANK_ANALYZER_STRATEGY";
pub(crate) const LINK_GRAPH_JULIA_RERANK_SERVICE_MODE_ENV: &str =
    "XIUXIAN_WENDAO_LINK_GRAPH_JULIA_RERANK_SERVICE_MODE";
pub(crate) const LINK_GRAPH_JULIA_RERANK_ANALYZER_CONFIG_PATH_ENV: &str =
    "XIUXIAN_WENDAO_LINK_GRAPH_JULIA_RERANK_ANALYZER_CONFIG_PATH";
pub(crate) const LINK_GRAPH_JULIA_RERANK_VECTOR_WEIGHT_ENV: &str =
    "XIUXIAN_WENDAO_LINK_GRAPH_JULIA_RERANK_VECTOR_WEIGHT";
pub(crate) const LINK_GRAPH_JULIA_RERANK_SIMILARITY_WEIGHT_ENV: &str =
    "XIUXIAN_WENDAO_LINK_GRAPH_JULIA_RERANK_SIMILARITY_WEIGHT";
#[cfg(test)]
pub(crate) const DEFAULT_LINK_GRAPH_JULIA_DEPLOYMENT_ARTIFACT_SCHEMA_VERSION: &str =
    xiuxian_wendao_julia::compatibility::link_graph::DEFAULT_JULIA_DEPLOYMENT_ARTIFACT_SCHEMA_VERSION;
pub(crate) const DEFAULT_LINK_GRAPH_RETRIEVAL_MODE: &str = "hybrid";
